# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
 :inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"}
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"}
         ]
  },

  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"}
                ]
  },

  :office1Router => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.254.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: "192.168.2.1", adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev-office1"},
                   {ip:"192.168.2.65", adapter: 4, netamsk: "255.255.255.192", virtualbox__intnet: "test-office1"},
		   {ip:"192.168.2.129", adapter: 5, netamsk: "255.255.255.192", virtualbox__intnet: "managers-office1"},
		   {ip:"192.168.2.193", adapter: 6, netamsk: "255.255.255.192", virtualbox__intnet: "office1-hw"}
	]
  },

  :office2Router => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.253.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
		   {ip: "192.168.1.1", adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "dev-office2"},
                   {ip:"192.168.1.129", adapter: 4, netamsk: "255.255.255.192", virtualbox__intnet: "test-office2"},
                   {ip:"192.168.1.193", adapter: 5, netamsk: "255.255.255.192", virtualbox__intnet: "office2-hw"}
                ]
  },

  :office1Server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "dev-office1"}
                ]
  },

  :office2Server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "dev-office2"}
                ]
  },


}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

	config.vm.provider "virtualbox" do |v|
          v.memory = 256
        end

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
	  echo 1 > /proc/sys/net/ipv4/ip_forward
	  for eth in /proc/sys/net/ipv4/conf/*/rp_filter
	  do
		echo 0 > $eth
	  done 
        SHELL

        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            yum install -y net-tools
	    sysctl net.ipv4.conf.all.forwarding=1
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
            ip route add 192.168.0.0/16 via 192.168.255.2
	    for DEV in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > $DEV; done
	    SHELL
        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
	    sysctl net.ipv4.ip_forward=1 #to send packets between interfaces
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
	    #yum install net-tools
	    #sudo ifconfig eth1:0 192.168.254.1 netmask 255.255.255.252 up
	    #sudo ifconfig eth1:1 192.168.253.1 netmask 255.255.255.252 up
	     cat <<EOT >> /etc/sysconfig/network-scripts/ifcfg-eth1:0
DEVICE=eth1:0
BOOTPROTO=static
IPADDR=192.168.254.1
NETMASK=255.255.255.252
ONBOOT=yes
EOT
              cat <<EOT >> /etc/sysconfig/network-scripts/ifcfg-eth1:1
DEVICE=eth1:1
BOOTPROTO=static
IPADDR=192.168.253.1
NETMASK=255.255.255.252
ONBOOT=yes
EOT
	    #ip route add 192.168.2.0/24 via 192.168.254.2 dev eth1:0
	    #ip route add 192.168.1.0/24 via 192.168.253.2 dev eth1:1
	    systemctl restart network
	    echo "192.168.2.0/24 via 192.168.254.2 dev eth1:0" >> /etc/sysconfig/network-scripts/route-eth1
            echo "192.168.1.0/24 via 192.168.253.2 dev eth1:1" >> /etc/sysconfig/network-scripts/route-eth1
	    systemctl restart network
	    for DEV in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > $DEV; done
	    echo 1 > /proc/sys/net/ipv4/ip_forward
            SHELL
        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
	    ip r del default
	    ip r add default via 192.168.0.1 dev eth1
            SHELL
        when "office1Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo "GATEWAY=192.168.254.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
	    systemctl restart network
	    for DEV in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > $DEV; done
            echo 1 > /proc/sys/net/ipv4/ip_forward
	    ip r del default
	    ip r add default via 192.168.254.1 dev eth1
	    SHELL
        when "office2Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo "GATEWAY=192.168.253.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
	    systemctl restart network
	    for DEV in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > $DEV; done
	    ip r del default
	    ip r add default via 192.168.253.1 dev eth1
	    echo 1 > /proc/sys/net/ipv4/ip_forward
            SHELL
        when "office1Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo "GATEWAY=192.168.2.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
	    ip r del default 
	    ip r add default via 192.168.2.1 dev eth1
            SHELL
        when "office2Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
            echo "GATEWAY=192.168.1.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
	    ip r del default
	    ip r add default via 192.168.1.1 dev eth1
            SHELL


        end

      end

  end


end

