---
- name: Install epel-release
  yum:
   name: epel-release
   state: latest
  tags:
   - package
   - epel


- name: Install Nginx server
  yum: 
   name: nginx
   state: latest
   #  notify: restart nginx

- name: enable service nginx
  systemd:
    name: nginx
    enabled: yes
    masked: no

- name: Replace NGINX config
  template:	    
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
