# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 250,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 250, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 250,
                        :port => 3
                },
                :sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 250, # Megabytes
                        :port => 4
                }

	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
	  config.vm.provision "file", source: "./watchlog.service", destination: "~/watchlog.service"
	  config.vm.provision "file", source: "./watchlog.timer", destination: "~/watchlog.timer"
	  config.vm.provision "file", source: "./watchlog.sh", destination: "~/watchlog.sh"
	  config.vm.provision "file", source: "./watchdog", destination: "~/watchdog"
	  config.vm.provision "file", source: "./watchlog.log", destination: "~/watchlog.log"
 	  
	  
	  config.vm.provision "file", source: "./spawn-fcgi.service", destination: "~/spawn-fcgi.service"

	
	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk
	      
	      cp /home/vagrant/watchlog.service /etc/systemd/system/watchlog.service
	      cp /home/vagrant/watchlog.timer /etc/systemd/system/watchlog.timer
	      cp /home/vagrant/watchlog.sh /opt/watchlog.sh
	      cp /home/vagrant/watchdog /etc/sysconfig/watchdog
	      cp /home/vagrant/watchlog.log /var/log/watchlog.log
	      
	      chmod 664 /etc/systemd/system/watchlog.service
	      chmod 664 /etc/systemd/system/watchlog.timer
	      chmod 764 /opt/watchlog.sh
	      systemctl start watchlog.timer


	      yum install epel-release -y && yum install spawn-fcgi php php-cli mod_fcgid httpd -y
	      cp /home/vagrant/spawn-fcgi.service /etc/systemd/system/spawn-fcgi.service
	      chmod 664 /etc/systemd/system/spawn-fcgi.service
	      sed -i 's/#SOCKET/SOCKET/g' /etc/sysconfig/spawn-fcgi
	      sed -i 's/#OPTIONS/OPTIONS/g' /etc/sysconfig/spawn-fcgi	      
		
 	      systemctl start spawn-fcgi

		
	      sed -i 's|EnvironmentFile\=\/etc\/sysconfig\/httpd|EnvironmentFile\=\/etc\/sysconfig\/httpd-\%i|' /usr/lib/systemd/system/httpd.service
	      mv /etc/sysconfig/httpd /etc/sysconfig/httpd-first
	      cp /etc/sysconfig/httpd-first /etc/sysconfig/httpd-second
	
	      sed -i 's|#OPTIONS=|OPTIONS=-f conf\/first\.conf|' /etc/sysconfig/httpd-first
	      sed -i 's|#OPTIONS=|OPTIONS=-f conf\/second\.conf|' /etc/sysconfig/httpd-second
	      mv /etc/httpd/conf/httpd.conf /etc/httpd/conf/first.conf
	      cp /etc/httpd/conf/first.conf /etc/httpd/conf/second.conf
	      sed -i "s|Listen 80|Listen 8080\\nPidFile \/var\/run\/httpd-second\.pid|" /etc/httpd/conf/second.conf

	      mv /usr/lib/systemd/system/httpd.service /usr/lib/systemd/system/httpd@.service
	
	      systemctl start httpd@first
	      systemctl start httpd@second

  	  SHELL

      end
  end
end

