# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 250,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 250, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 250,
                        :port => 3
                },
                :sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 250, # Megabytes
                        :port => 4
                }


	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y redhat-lsb-core wget rpmdevtools rpm-build createrepo yum-utils epel-release
        rpmdev-setuptree
  	  SHELL
    config.vm.provision "file", source: "./ps_ax_otus.spec", destination: "~/ps_ax_otus.spec"
    config.vm.provision "file", source: "./ps_ax.sh", destination: "~/ps_ax.sh"
    config.vm.provision "file", source: "./nginx.conf", destination: "~/nginx.conf"

    box.vm.provision "shell", inline: <<-SHELL
        cp /home/vagrant/ps_ax_otus.spec /root/rpmbuild/SPECS
        cp /home/vagrant/ps_ax.sh /root/rpmbuild/SOURCES
        rpmbuild -ba /root/rpmbuild/SPECS/ps_ax_otus.spec


        yum install -y nginx
        mkdir /usr/share/nginx/html/repo
        cp /root/rpmbuild/RPMS/x86_64/otus_ps_ax-1-0.x86_64.rpm /usr/share/nginx/html/repo/
        createrepo /usr/share/nginx/html/repo/
        
        cp -f ./nginx.conf /etc/nginx/nginx.conf

        echo "[otus]" >> ./otus.repo
        echo "name=otus-linux" >> ./otus.repo
        echo "baseurl=http://localhost/repo" >> ./otus.repo
        echo "gpgcheck=0" >> ./otus.repo
        echo "enabled=1" >> ./otus.repo

        cp ./otus.repo /etc/yum.repos.d/otus.repo

        systemctl start nginx
    SHELL

	  # box.vm.provision "shell", path: "/home/lek/otus/DZ_2_RAID/raid10_auto_creation.sh"
      end
  end
end

