---
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart audit
  service:
    name: auditd
    state: restarted
